### ISSUE TITLE
Auto rename all created notes from "new note" to  "DDMMYYYYhhmmss", exept daily notes

### ISSUE THREAD

**Issue by rapatar** [mnaoumov/obsidian-smart-rename#4]
- Adding text that was converted into link to new notes aliases
- Ability to add exeption folders, for example **Daily notes**
- **Note composer** plugin compatibilty (where extracted text "Lorem ispum" transforms to ![[DDMMYYYYhhmss]])
  - Or paragraph like:
    "Lorem ipsum.
     Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." transforms to 
   "[[DDMMYYYYhhmss|Lorem ispum]]"
- Cursor goes [[[DDMMYYYYhhmss|**Here**]] if new noted opened at background
- Ability to make custom frontmatter template, for example
 ```
  ---
aliases: 
  - note name
tags:
  - tag
source
  - link
 ---
```

**Comment by Medullitus** [comment]
Is this a request or bug??

**Comment by rapatar** [comment]
This is request of function like Unique note creator, but applied to all
notes.

For example, when you [[click]] on link for note that wasn't created yet,
the new note will be created with "click" added to aliase,
YYYYMMDDhhmmss.md format file name, and [[click]] in original note will be
replaced with [[YYYYMMDDhhmmss|click]].
сб, 8 июн. 2024 г., 12:49 Medullitus ***@***.***>:

**Comment by Medullitus** [comment]
I have a issue maybe it's a similar issue like yours. What can you say about this? My issue is that I have lots of notes with title that consist unvalid characters. I need to have an option to convert all of them at once

**Comment by Medullitus** [comment]
I mean this 

![1](https://github.com/mnaoumov/obsidian-smart-rename/assets/52373851/57076932-ee63-4e32-b50d-c49e10a9096f)
![2](https://github.com/mnaoumov/obsidian-smart-rename/assets/52373851/d84f652d-dbb8-4aac-9a7d-10c8c8e8399b)
![3](https://github.com/mnaoumov/obsidian-smart-rename/assets/52373851/3f90e90b-7cb8-430a-906d-4dba5d73af78)

**Comment by rapatar** [comment]
I think it can be done by batch renaming by regular expression. Search the
way for batch renaming with regex, and ask ChatGPT to give you a regex
command form. If I understand you correctly, you want to rename markdown
file names, not the title.
The regex command will replace "!" with "." symbols for example.
Iyi günlər :)

сб, 8 июн. 2024 г., 22:22 Medullitus ***@***.***>:

**Comment by rapatar** [comment]
Basicly it can be done by python script, ChatGPT will guide you. But don't
forget to make a BACKUP of your vault first!

вс, 9 июн. 2024 г., 01:17 Dadash Mukhtarov ***@***.***>:

**Comment by Medullitus** [comment]
This is a great suggestion! Thank you. But I have a question. If I understood you correctly, can I apply the full name from the title to the file name? Are you sure ChatGPT can show how to do this? By the way, how nice to meet an Azerbaijani Turk! Merhaba, gardaşım!

**Comment by rapatar** [comment]
Merhaba qardaş.
I think to avoid problems with invalud characters in titles and file names,
better to use "aliases" in front matter. Aliases can containt any character
and will not cause a problem.
There is a plugin in obsidian to show data from aliases as a file name. So
your note file name can be whatever you want.
That's why I did that feature request to this plugin.
In my obsidian workflow all notes have filename like:
20240609141156.md
And content is like:
---
aliases: Actual note title
---
Content of note.

Below plugin will display value from frontmatter (alias) as note name in
file manager and graph
https://github.com/Snezhig/obsidian-front-matter-title

вс, 9 июн. 2024 г., 04:53 Medullitus ***@***.***>:

**Comment by mnaoumov** [comment]
This FR is beyond the scope of this plugin

Maybe this plugin or similar will suit you better

https://github.com/TheLoneWanderer4/obsidian-uuid-title

**Comment by Medullitus** [comment]
> This FR is beyond the scope of this plugin
> 
> Maybe this plugin or similar will suit you better
> 
> https://github.com/TheLoneWanderer4/obsidian-uuid-title

Thank you. I will try it. But you might consider developing your plugin for users like me, who have transitioned from note-taking apps like Joplin and are facing difficulties. We owe a lot to volunteer developers like you. Thanks!

**Comment by mnaoumov** [comment]
@Medullitus I personally also migrated from Joplin 3 years ago and was solving similar issues on my own. But as it is a one-time task, it's not worth making a plugin, as it is hard to please everyone. It's easier to write a script to perform those one-time migrations.

**Comment by Medullitus** [comment]
I understand, but there’s an issue about this. Users who don’t have experience in coding might find the approach you see as simple to be very valuable. For example, I have around 30,000 notes. Instead of editing the titles one by one, it would be ideal to organize them with such a simple solution and automatically integrate the note names in the title into the note header.

**Comment by mnaoumov** [comment]
@Medullitus feel free to open another issue on the forum and I will reply there. For historical purposes, leave the link to your forum post here

**Comment by Medullitus** [comment]
Here's the link: https://forum.obsidian.md/t/reopen-automating-the-renaming-of-notes-with-unaccepted-characters-in-obsidian/93871

Thank you so much bro!
