### ISSUE TITLE
Plugin Conflict - filename heading sync

### ISSUE THREAD

**Issue by erauner12** [mnaoumov/obsidian-smart-rename#6]
Hello,

I noticed that when this plugin is enabled:
[dvcrn/obsidian-filename-heading-sync: Obisdian.md plugin to keep the filename and the first header of the file in sync](https://github.com/dvcrn/obsidian-filename-heading-sync)
- when smart rename is invoked, the name of the file is in fact changed but the `aliases` is not appended to?

current behavior (filename heading sync enabled):
- smart rename file
- `aliases` value changes to the new value that smart rename named the file to

desired behavior (filename heading sync enabled):
- smart rename file
- `aliases` old value appended to `aliases`
- file is renamed
- new value is appended to `aliases`

I can confirm that the desired behavior does work when I disable this plugin.

Let me know what you think, thank you!

**Comment by mnaoumov** [comment]
@erauner12 thank you for the bug report. The problem is that when note file renamed, different plugins process this rename asynchronously and in the unpredictable order. I will investigate how to mitigate i

**Comment by erauner12** [comment]
Great thank you so much 🙂

**Comment by mnaoumov** [comment]
@erauner12 I could not reproduce the issue. However, I made a new build which also has setting to sync with the header. This might help with your issue. Please test.

As a side node, I am also using the [Obsidian Filename Heading Sync](https://github.com/dvcrn/obsidian-filename-heading-sync) plugin but I use it only manually. The reason for that is sometimes I want to keep in header some characters that impossible to use in the file name (such as `/`)

**Comment by erauner12** [comment]
Thank you! Will try this afternoon
