### ISSUE TITLE
Auto Rename Feature PLZ

### ISSUE THREAD

**Issue by Medullitus** [mnaoumov/obsidian-smart-rename#8]
Hello. Thanks for AMAZING app. I have lots of notes with title that consist unvalid characters. Can you plz make an option to convert all of them at once? THX!!!

**Comment by mnaoumov** [comment]
Please show an example of titles you need to rename

**Comment by mnaoumov** [comment]
Closing as no response provided

**Comment by Medullitus** [comment]
Heyy wait i'm here don't close it

> Closing as no response provided

Sure! Here's the translation:

Hey, I'm here. Please don't close the topic. You are replying to my topic after 5 months. I didn't see the notification for your reply, and you're closing it after a month...

**Comment by mnaoumov** [comment]
@Medullitus Sure, provide the information I need to investigate your FR

**Comment by Medullitus** [comment]
> @Medullitus Sure, provide the information I need to investigate your FR

Thank you for reopening it. I've elaborated on the topic in this link. Do you have a chance to take a look?

https://forum.obsidian.md/t/automating-the-renaming-of-notes-with-unaccepted-characters-in-obsidian/83447

**Comment by mnaoumov** [comment]
So if I understand correctly, you want a way to go through all your notes and rename them accordingly to their `title` key in the frontmatter but making the valid file names.

1. This is out of the scope of this plugin. So the issue will be closed
2. It's not too difficult to write a script that does what you need. Let me know if you need me to help

**Comment by mnaoumov** [comment]
See my comment https://github.com/mnaoumov/obsidian-smart-rename/issues/4#issuecomment-2564154386

Closing this issue as not relevant
